# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PodsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodsTest

  pod 'TCJDemoSpecs', :git =>'https://github.com/Tcj1988/TCJDemoSpecs.git',:tag => '0.0.1'
  
end
